#!/usr/bin/python
# -*- coding: utf-8 -*-
import paramiko

def open_ssh_connection(user, password, host, ssh_port=22,  ssh_timeout=3):
    client = paramiko.SSHClient()
    client.set_missing_host_key_policy(paramiko.AutoAddPolicy())
    try:
        client.connect(host, port=ssh_port, username=user, password=password, timeout=ssh_timeout)
        return client
    except Exception as e:
        print(e)
        return


def execute_commands(ssh_client, commands):
    for i in range(len(commands)):
        stdin, stdout, stderr = ssh_client.exec_command(commands[i])
        err_list = stderr.readlines()
        if len(err_list) > 0:
            print('%s has errors %s' % (commands[i], err_list[0]))
            return
        else:
            return 1
        # for out in stdout.readlines():
        #    print(out)


def upload_file_via_ssh(ssh_client, lfile, rfile):
    try:
        '''
        conn = paramiko.Transport((hostname, port))
        conn.connect(username=user, password=password)
        sftp = paramiko.SFTPClient.from_transport(conn)
        '''
        sftp = ssh_client.open_sftp()
        sftp.put(lfile, rfile)
    except Exception as e:
        print(e)


def download_file_via_ssh(ssh_client, rfile, lfile):
    try:
        sftp = ssh_client.open_sftp()
        sftp.get(rfile, lfile)
    except Exception as e:
        print(e)


def close_ssh_connection(ssh_client):
    ssh_client.close()


def main():
    commands = ['ls /root/.ssh || mkdir /root/.ssh']
    ssh_info = {'host': '192.168.1.101',
                'ssh_port': 22,
                'user': 'oracle',
                'password': 'oracle'}
    src_file = '/root/.ssh/authentication.keys'
    dest_file = '/root/.ssh/authentication.keys'
    conn_client = open_ssh_connection(**ssh_info)
    if conn_client:
        if execute_commands(conn_client, commands):
            upload_file_via_ssh(conn_client, src_file, dest_file)
        close_ssh_connection(conn_client)


if __name__ == '__main__':
    main()
    ####
